from datetime import datetime, timezone
import hashlib
import logging
import re
from typing import Any

from app.models.document_content import (
    ContentHierarchy,
    ContentUnit,
    SourceLocation,
)


logger = logging.getLogger(__name__)

CODE_HEADER_TERMS = {
    "code",
    "value",
    "valeur",
    "status",
    "statut",
    "error",
    "erreur",
    "return",
    "response",
}
MEANING_HEADER_TERMS = {
    "meaning",
    "definition",
    "description",
    "signification",
    "details",
    "detail",
    "message",
}
FRONT_MATTER_TITLES = {
    "table of contents",
    "contents",
    "list of tables",
    "title page",
    "about this manual",
}
INDEX_TITLES = {
    "index",
}
STRUCTURAL_SUBSECTION_LABELS = (
    "attributes",
    "description",
    "usage",
    "field edits",
    "reject codes",
    "valid values",
    "generated by",
    "programming rules",
    "requirements",
    "examples",
    "notes",
    "overview",
)


def clean_text(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def normalize_text(value: Any) -> str:
    return clean_text(value).lower()


def stable_unit_id(*parts: Any) -> str:
    raw = "|".join(str(part or "") for part in parts)
    digest = hashlib.sha1(raw.encode("utf-8")).hexdigest()[:20]

    return f"cu_{digest}"


def nullable_int(value: Any) -> int | None:
    if isinstance(value, int):
        return value

    if isinstance(value, str) and value.strip().isdigit():
        return int(value.strip())

    return None


def parse_hierarchy(heading: str | None) -> ContentHierarchy:
    """Extrait seulement la hierarchie explicitement visible."""
    if not heading:
        return ContentHierarchy()

    parts = [
        clean_text(part)
        for part in str(heading).split(">")
        if clean_text(part)
    ]
    chapter = None
    section = None
    subsection = None

    for part in parts:
        if chapter is None and re.match(r"^chapter\s+\d+\b", part, re.I):
            chapter = part
            continue

        match = re.match(r"^(?P<number>\d+(?:\.\d+){0,6})\b", part)

        if not match:
            continue

        number = match.group("number")

        if section is None:
            section = number
        else:
            subsection = number

    return ContentHierarchy(
        chapter=chapter,
        section=section,
        subsection=subsection,
        title=parts[-1] if parts else None,
    )


def detect_document_zone(
    hierarchy: ContentHierarchy,
    section: dict[str, Any] | None = None,
) -> str:
    """Classe grossierement la zone documentaire sans supprimer son contenu."""
    section = section or {}
    title = normalize_text(hierarchy.title)
    heading = normalize_text(section.get("heading"))

    if title in INDEX_TITLES or heading in INDEX_TITLES:
        return "index"

    if (
        title in FRONT_MATTER_TITLES
        or heading in FRONT_MATTER_TITLES
    ):
        return "front_matter"

    if title.startswith("appendix") or heading.startswith("appendix"):
        return "appendix"

    return "body"


def normalize_field_entity(raw_number: str) -> str:
    if "." in raw_number:
        left, right = raw_number.split(".", 1)
        return f"{int(left):03d}.{right}" if left.isdigit() else raw_number

    return f"{int(raw_number):03d}" if raw_number.isdigit() else raw_number


def extract_primary_entities(
    text: str,
    heading: str | None = None,
    section: dict[str, Any] | None = None,
    document_zone: str = "body",
) -> dict[str, Any]:
    """Extrait le sujet principal quand il est explicite dans les metadonnees."""
    section = section or {}
    entities: dict[str, Any] = {}

    if document_zone in {"front_matter", "index"}:
        return entities

    field_number = section.get("field_number")

    if field_number:
        entities["field_number"] = normalize_field_entity(str(field_number))

    field_name = section.get("field_name")

    if field_name:
        entities["field_name"] = str(field_name)

    if "field_number" not in entities:
        field_match = re.search(
            r"\b(?:field|fld|champ|data\s+element)\s*\(?0*(\d{1,3}(?:\.\d+)?)\)?\s*[—-]\s*([^>\n]+)",
            str(heading or ""),
            flags=re.I,
        )

        if field_match:
            raw_number = field_match.group(1)
            entities["field_number"] = normalize_field_entity(raw_number)
            entities["field_name"] = clean_text(field_match.group(2))

    message_match = re.search(
        r"\b(?:mti|message\s+type)\s*[:=]?\s*\[?(\d{4})\]?",
        str(heading or ""),
        flags=re.I,
    )

    if message_match:
        entities["message_type"] = message_match.group(1)

    return entities


def extract_referenced_entities(
    text: str,
    document_zone: str = "body",
) -> dict[str, Any]:
    """Garde les entites citees sans les confondre avec le sujet principal."""
    if document_zone in {"front_matter", "index"}:
        return {}

    field_numbers = []

    for match in re.finditer(
        r"\b(?:field|fld|champ|data\s+element)\s*\(?0*(\d{1,3}(?:\.\d+)?)\)?",
        text,
        flags=re.I,
    ):
        field_numbers.append(normalize_field_entity(match.group(1)))

    message_types = re.findall(
        r"\b(?:mti|message\s+type)?\s*\[?((?:0[1248]00)|(?:0[1248]10)|(?:1[1248]10))\]?",
        text,
        flags=re.I,
    )
    referenced: dict[str, Any] = {}

    if field_numbers:
        referenced["field_numbers"] = list(dict.fromkeys(field_numbers))

    if message_types:
        referenced["message_types"] = list(dict.fromkeys(message_types))

    return referenced


def extract_generic_entities(
    text: str,
    heading: str | None = None,
    section: dict[str, Any] | None = None,
    document_zone: str = "body",
) -> dict[str, Any]:
    """Compatibilite: expose seulement les entites primaires historiques."""
    return extract_primary_entities(
        text,
        heading=heading,
        section=section,
        document_zone=document_zone,
    )


def line_starts_note(line: str) -> bool:
    return bool(re.match(r"^\s*(note|remarque)\b[:\s-]*", line, re.I))


def line_starts_example(line: str) -> bool:
    return bool(re.match(r"^\s*(example|exemple)\b[:\s-]*", line, re.I))


def split_table_cells(line: str) -> list[str]:
    if "|" in line:
        return [
            clean_text(cell)
            for cell in line.strip().strip("|").split("|")
        ]

    if "\t" in line:
        return [
            clean_text(cell)
            for cell in line.split("\t")
        ]

    return []


def is_table_like_line(line: str) -> bool:
    cells = split_table_cells(line)

    return len([cell for cell in cells if cell]) >= 2


def table_lines_from_text(text: str) -> list[str]:
    return [
        line
        for line in str(text or "").splitlines()
        if is_table_like_line(line)
    ]


def header_supports_code_mapping(cells: list[str]) -> bool:
    normalized_cells = [normalize_text(cell) for cell in cells]
    first = normalized_cells[0] if normalized_cells else ""
    rest = " ".join(normalized_cells[1:])

    return (
        any(term in first for term in CODE_HEADER_TERMS)
        and any(term in rest for term in MEANING_HEADER_TERMS)
    )


def looks_like_code(value: str) -> bool:
    cleaned = clean_text(value).strip("'\"[]().,:;")

    return bool(re.fullmatch(r"(?:\d{2}|[A-Z]\d|[A-Z]{2}\d{0,2})(?:\.\d+)?", cleaned))


def looks_like_meaning(value: str) -> bool:
    text = clean_text(value)

    if len(text) < 3:
        return False

    if looks_like_code(text):
        return False

    return bool(re.search(r"[A-Za-z]", text))


def explicit_code_mapping_from_line(line: str) -> tuple[str, str] | None:
    if line_starts_note(line) or line_starts_example(line):
        return None

    match = re.match(
        r"^\s*['\"]?(?P<code>(?:\d{2}|[A-Z]\d|[A-Z]{2}\d{0,2}))['\"]?\s*(?:=|:|->|-->)\s*(?P<meaning>.+?)\s*$",
        line,
        flags=re.I,
    )

    if not match:
        return None

    code = clean_text(match.group("code")).upper()
    meaning = clean_text(match.group("meaning")).strip(" .;")

    if looks_like_code(code) and looks_like_meaning(meaning):
        return code, meaning

    return None


def normalize_table_code(token: str) -> str:
    """Retire des suffixes de note quand le code tabulaire est identifiable."""
    cleaned = clean_text(token).strip("'\"[]().,:;")
    match = re.match(r"^(?P<code>\d{2}|[A-Z]\d)(?P<notes>(?:\d|,\d+)*)$", cleaned)

    if match:
        return match.group("code").upper()

    match = re.match(r"^(?P<code>[A-Z]{2}\d{0,2})$", cleaned)

    if match:
        return match.group("code").upper()

    return cleaned.upper()


def looks_like_table_code_token(value: str) -> bool:
    return bool(
        re.fullmatch(
            r"(?:\d{2}|[A-Z]\d)(?:\d{1,2}|,\d+)*|[A-Z]{2}\d{0,2}",
            clean_text(value),
        )
    )


def clean_flattened_table_lines(text: str) -> list[str]:
    ignored = {
        "issr",
        "stip",
        "inq",
        "upd",
        "adv",
        "0x20",
        "0110 msgs",
        "0410 msgs",
        "031x msgs",
    }
    lines = []

    for line in str(text or "").splitlines():
        cleaned = clean_text(line)
        normalized = normalize_text(cleaned)

        if not cleaned:
            continue

        if normalized in ignored:
            continue

        if re.search(
            r"\b(?:visa confidential|all rights reserved|technical specifications|1 jun 2019)\b",
            normalized,
        ):
            continue

        if re.fullmatch(r"\d+-\d+", cleaned):
            continue

        lines.append(cleaned)

    return lines


class FlattenedTableDetector:
    """Reconstruit prudemment des tables OCR quand les colonnes sont aplaties."""

    HEADER_PATTERNS = (
        ("code", "definition"),
        ("code", "meaning"),
        ("code", "description"),
        ("value", "definition"),
        ("value", "description"),
        ("command", "response", "meaning"),
        ("error", "description"),
        ("response", "code"),
    )

    @staticmethod
    def header_index(lines: list[str]) -> int | None:
        lowered = [normalize_text(line) for line in lines]

        for index, line in enumerate(lowered):
            window = " ".join(lowered[index:index + 6])

            if any(
                all(term in window for term in pattern)
                for pattern in FlattenedTableDetector.HEADER_PATTERNS
            ):
                return index

        return None

    @staticmethod
    def row_start(line: str) -> tuple[str, str] | None:
        cleaned = clean_text(line)

        if looks_like_table_code_token(cleaned):
            return normalize_table_code(cleaned), ""

        match = re.match(
            r"^(?P<token>(?:\d{2}|[A-Z]\d)(?:\d{1,2}|,\d+)*|[A-Z]{2}\d{0,2})\s+(?P<meaning>[A-Za-z].+)$",
            cleaned,
        )

        if match:
            return (
                normalize_table_code(match.group("token")),
                clean_text(match.group("meaning")),
            )

        return None

    @staticmethod
    def detect(text: str) -> dict[str, Any] | None:
        lines = clean_flattened_table_lines(text)
        header_index = FlattenedTableDetector.header_index(lines)

        if header_index is None:
            return None

        title = "Table"

        for index in range(max(0, header_index - 4), header_index):
            if re.search(r"\btable\b", lines[index], flags=re.I):
                title = lines[index]

        rows = []
        current: dict[str, Any] | None = None

        for line in lines[header_index + 1:]:
            if normalize_text(line) in {"code", "definition", "meaning", "description"}:
                continue

            start = FlattenedTableDetector.row_start(line)

            if start:
                if current and current.get("meaning_parts"):
                    rows.append(current)

                current = {
                    "code": start[0],
                    "meaning_parts": [start[1]] if start[1] else [],
                }
                continue

            if current is None:
                continue

            if looks_like_meaning(line):
                current["meaning_parts"].append(line)

        if current and current.get("meaning_parts"):
            rows.append(current)

        normalized_rows = []

        for row in rows:
            meaning = clean_text(" ".join(row.get("meaning_parts") or []))

            if not looks_like_code(row.get("code", "")) or not looks_like_meaning(meaning):
                continue

            normalized_rows.append({
                "code": row["code"],
                "meaning": meaning,
            })

        if len(normalized_rows) < 3:
            return None

        return {
            "title": title,
            "headers": ["Code", "Definition"],
            "rows": normalized_rows,
            "confidence": 0.86,
        }


def classify_non_table_content(
    text: str,
    heading: str | None,
    section: dict[str, Any],
) -> tuple[str, float]:
    """Classe prudemment un contenu non-table en utilisant texte + contexte."""
    normalized = normalize_text(text)
    heading_normalized = normalize_text(heading)
    content_type = str(section.get("content_type") or "")

    if not normalized:
        return "unknown", 0.0

    first_line = text.splitlines()[0] if text.splitlines() else text

    if line_starts_note(first_line):
        return "note", 0.95

    if line_starts_example(first_line):
        return "example", 0.95

    if re.search(r"\b(must|required|shall|obligatoire|doit|ne doit pas)\b", normalized):
        return "rule", 0.72

    if re.search(r"\b(step|etape|procedure|processus)\b", normalized):
        return "procedure", 0.65

    if re.search(r"\b(flow|workflow|sequence|enchainement)\b", normalized):
        return "workflow", 0.65

    if content_type == "field_attributes" and re.search(
        r"\b(length|longueur|type|format|byte|octet|fixed)\b",
        normalized,
    ):
        return "field_attribute", 0.88

    if content_type == "field_usage" and re.search(
        r"\b(used|usage|present|request|response|utilise)\b",
        normalized,
    ):
        return "field_usage", 0.86

    if content_type == "field_definition" or (
        section.get("field_number")
        and re.search(r"\b(description|defines|contains|contient|definit)\b", normalized)
    ):
        return "field_description", 0.78

    if section.get("field_number") and "field" in heading_normalized:
        return "field_description", 0.62

    if re.search(r"\b(is|are|means|signifie|represente|definition)\b", normalized):
        return "definition", 0.62

    if re.search(r"[A-Za-z0-9]", normalized):
        return "paragraph", 0.7

    return "unknown", 0.3


def title_from_structural_heading(raw_title: str) -> str:
    title = clean_text(raw_title)

    for label in STRUCTURAL_SUBSECTION_LABELS:
        pattern = re.compile(rf"^({re.escape(label)})\b", re.I)
        match = pattern.search(title)

        if match:
            return clean_text(title[:match.end()])

    words = title.split()

    if len(words) > 8:
        return " ".join(words[:8])

    return title


def structural_heading_matches(text: str) -> list[re.Match[str]]:
    labels = "|".join(re.escape(label) for label in STRUCTURAL_SUBSECTION_LABELS)
    pattern = re.compile(
        rf"(?<!\d)(?P<number>\d+(?:\.\d+){{1,6}})\s+"
        rf"(?P<title>(?:{labels})\b|[A-Z][A-Za-z0-9 /(),—-]{{2,80}})",
        flags=re.I,
    )

    return list(pattern.finditer(text))


def hierarchy_for_subsection(
    base: ContentHierarchy,
    number: str,
    raw_title: str,
) -> ContentHierarchy:
    title = f"{number} {title_from_structural_heading(raw_title)}"

    if "." in number:
        section = ".".join(number.split(".")[:2])
    else:
        section = base.section

    return ContentHierarchy(
        chapter=base.chapter,
        section=section or base.section,
        subsection=number,
        title=title,
    )


def structural_subsection_segments(
    text: str,
    hierarchy: ContentHierarchy,
) -> list[dict[str, Any]]:
    """Decoupe un chunk en sous-sections internes numerotees si elles existent."""
    matches = structural_heading_matches(text)

    if not matches:
        return [{
            "text": text,
            "hierarchy": hierarchy,
            "offset": 0,
        }]

    segments = []
    first = matches[0]

    if clean_text(text[:first.start()]):
        segments.append({
            "text": text[:first.start()],
            "hierarchy": hierarchy,
            "offset": 0,
        })

    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        number = match.group("number")
        raw_title = match.group("title")
        segments.append({
            "text": text[match.start():end],
            "hierarchy": hierarchy_for_subsection(
                hierarchy,
                number,
                raw_title,
            ),
            "offset": index + 1,
        })

    return [
        segment
        for segment in segments
        if clean_text(segment["text"])
    ] or [{
        "text": text,
        "hierarchy": hierarchy,
        "offset": 0,
    }]


def source_location_from_section(section: dict[str, Any]) -> SourceLocation:
    return SourceLocation(
        pdf_page=nullable_int(section.get("page")),
        printed_page=section.get("page_document"),
        sheet=section.get("sheet"),
        row_start=nullable_int(section.get("paragraph")),
        row_end=nullable_int(section.get("paragraph")),
        section_index=nullable_int(section.get("section_index")),
        chunk_index=nullable_int(section.get("chunk_index")),
    )


def source_chunk_id(
    document_id: str,
    section: dict[str, Any],
) -> str | None:
    section_index = section.get("section_index")
    chunk_index = section.get("chunk_index")

    if section_index is None and chunk_index is None:
        return None

    return f"{document_id}:{section_index}:{chunk_index}"


class ContentUnitExtractor:
    """Transforme les chunks existants en unites documentaires generiques."""

    @staticmethod
    def extract(
        *,
        sections: list[dict[str, Any]],
        document: dict[str, Any],
    ) -> list[dict[str, Any]]:
        document_id = str(document.get("_id") or document.get("document_id") or "")

        if not document_id:
            return []

        now = datetime.now(timezone.utc)
        units: list[ContentUnit] = []

        for section in sorted(
            sections,
            key=lambda item: (
                int(item.get("section_index") or 0),
                int(item.get("chunk_index") or 0),
            ),
        ):
            units.extend(
                ContentUnitExtractor.extract_from_section(
                    section=section,
                    document=document,
                    document_id=document_id,
                )
            )

        return [
            {
                **unit.model_dump(),
                "created_at": now,
            }
            for unit in units
        ]

    @staticmethod
    def extract_from_section(
        *,
        section: dict[str, Any],
        document: dict[str, Any],
        document_id: str,
    ) -> list[ContentUnit]:
        text = str(section.get("text") or "")
        heading = section.get("heading")
        hierarchy = parse_hierarchy(heading)
        document_zone = detect_document_zone(hierarchy, section)
        location = source_location_from_section(section)
        section_object_id = section.get("_id")
        source_section_id = str(section_object_id) if section_object_id else None
        chunk_id = source_chunk_id(document_id, section)
        section_index = int(section.get("section_index") or 0)
        chunk_index = int(section.get("chunk_index") or 0)
        base_order = (section_index * 10_000) + (chunk_index * 100)
        source = document.get("original_filename") or section.get("source")
        units: list[ContentUnit] = []

        if heading:
            heading_id = stable_unit_id(
                document_id,
                section_index,
                chunk_index,
                "heading",
                heading,
            )
            units.append(
                ContentUnit(
                    unit_id=heading_id,
                    document_id=document_id,
                    conversation_id=document.get("conversation_id"),
                    agent=document.get("agent"),
                    source=source,
                    hierarchy=hierarchy,
                    document_zone=document_zone,
                    content_type="heading",
                    entities=extract_generic_entities(
                        "",
                        heading=heading,
                        section=section,
                        document_zone=document_zone,
                    ),
                    primary_entities=extract_primary_entities(
                        "",
                        heading=heading,
                        section=section,
                        document_zone=document_zone,
                    ),
                    referenced_entities={},
                    content=clean_text(heading),
                    raw_text=clean_text(heading),
                    source_location=location,
                    source_section_id=source_section_id,
                    source_chunk_id=chunk_id,
                    document_order=base_order,
                    parsing_confidence=0.9,
                )
            )

        for segment in structural_subsection_segments(text, hierarchy):
            segment_text = segment["text"]
            segment_hierarchy = segment["hierarchy"]
            segment_offset = int(segment["offset"] or 0)
            segment_order = base_order + (segment_offset * 1_000)

            table_units = ContentUnitExtractor.extract_table_units(
                text=segment_text,
                section=section,
                document=document,
                document_id=document_id,
                hierarchy=segment_hierarchy,
                location=location,
                source_section_id=source_section_id,
                source_chunk_id=chunk_id,
                source=source,
                base_order=segment_order,
                document_zone=document_zone,
            )

            if table_units:
                units.extend(table_units)
                continue

            content_type, confidence = classify_non_table_content(
                text=segment_text,
                heading=segment_hierarchy.title or heading,
                section=section,
            )
            unit_id = stable_unit_id(
                document_id,
                section_index,
                chunk_index,
                segment_offset,
                content_type,
                segment_text,
            )

            primary_entities = extract_primary_entities(
                segment_text,
                heading=segment_hierarchy.title or heading,
                section=section,
                document_zone=document_zone,
            )
            units.append(
                ContentUnit(
                    unit_id=unit_id,
                    document_id=document_id,
                    conversation_id=document.get("conversation_id"),
                    agent=document.get("agent"),
                    source=source,
                    hierarchy=segment_hierarchy,
                    document_zone=document_zone,
                    content_type=content_type,
                    entities=primary_entities,
                    primary_entities=primary_entities,
                    referenced_entities=extract_referenced_entities(
                        segment_text,
                        document_zone=document_zone,
                    ),
                    content=clean_text(segment_text),
                    raw_text=clean_text(segment_text),
                    source_location=location,
                    source_section_id=source_section_id,
                    source_chunk_id=chunk_id,
                    document_order=segment_order + 1,
                    parsing_confidence=confidence,
                )
            )

        return units

    @staticmethod
    def extract_table_units(
        *,
        text: str,
        section: dict[str, Any],
        document: dict[str, Any],
        document_id: str,
        hierarchy: ContentHierarchy,
        location: SourceLocation,
        source_section_id: str | None,
        source_chunk_id: str | None,
        source: str | None,
        base_order: int,
        document_zone: str,
    ) -> list[ContentUnit]:
        table_lines = table_lines_from_text(text)
        flattened_table = None
        explicit_mapping = None

        if document_zone not in {"front_matter", "index"}:
            flattened_table = FlattenedTableDetector.detect(text)

            if not table_lines and not flattened_table:
                non_empty_lines = [
                    line
                    for line in str(text or "").splitlines()
                    if clean_text(line)
                ]

                if len(non_empty_lines) == 1:
                    explicit_mapping = explicit_code_mapping_from_line(non_empty_lines[0])

        if not table_lines and not explicit_mapping and not flattened_table:
            return []

        units: list[ContentUnit] = []
        table_id = stable_unit_id(
            document_id,
            section.get("section_index"),
            section.get("chunk_index"),
            "table",
            hierarchy.title,
            text[:200],
        )

        if flattened_table:
            table_title = flattened_table["title"] or hierarchy.title or "Table"
            table_entities = extract_primary_entities(
                text,
                heading=section.get("heading"),
                section=section,
                document_zone=document_zone,
            )
            units.append(
                ContentUnit(
                    unit_id=table_id,
                    document_id=document_id,
                    conversation_id=document.get("conversation_id"),
                    agent=document.get("agent"),
                    source=source,
                    hierarchy=hierarchy,
                    document_zone=document_zone,
                    content_type="table",
                    entities=table_entities,
                    primary_entities=table_entities,
                    referenced_entities=extract_referenced_entities(
                        text,
                        document_zone=document_zone,
                    ),
                    content=clean_text(table_title),
                    raw_text=clean_text(text),
                    source_location=location,
                    source_section_id=source_section_id,
                    source_chunk_id=source_chunk_id,
                    document_order=base_order + 1,
                    parsing_confidence=flattened_table["confidence"],
                )
            )

            for row_index, row in enumerate(flattened_table["rows"], start=1):
                code = row["code"]
                meaning = row["meaning"]
                row_content = f"{code} | {meaning}"
                row_id = stable_unit_id(
                    document_id,
                    section.get("section_index"),
                    section.get("chunk_index"),
                    "flattened_table_row",
                    row_index,
                    row_content,
                )
                row_entities = dict(table_entities)
                row_entities["code"] = code
                units.append(
                    ContentUnit(
                        unit_id=row_id,
                        document_id=document_id,
                        conversation_id=document.get("conversation_id"),
                        agent=document.get("agent"),
                        source=source,
                        hierarchy=hierarchy,
                        document_zone=document_zone,
                        content_type="table_row",
                        entities=row_entities,
                        primary_entities=row_entities,
                        referenced_entities={},
                        content=row_content,
                        raw_text=row_content,
                        source_location=location,
                        source_section_id=source_section_id,
                        source_chunk_id=source_chunk_id,
                        document_order=base_order + 1 + row_index,
                        parent_unit_id=table_id,
                        parsing_confidence=0.84,
                    )
                )

                mapping_id = stable_unit_id(
                    document_id,
                    section.get("section_index"),
                    section.get("chunk_index"),
                    "flattened_code_mapping",
                    code,
                    meaning,
                )
                units.append(
                    ContentUnit(
                        unit_id=mapping_id,
                        document_id=document_id,
                        conversation_id=document.get("conversation_id"),
                        agent=document.get("agent"),
                        source=source,
                        hierarchy=hierarchy,
                        document_zone=document_zone,
                        content_type="code_mapping",
                        entities=row_entities,
                        primary_entities=row_entities,
                        referenced_entities={},
                        content=meaning,
                        raw_text=row_content,
                        source_location=location,
                        source_section_id=source_section_id,
                        source_chunk_id=source_chunk_id,
                        document_order=base_order + 500 + row_index,
                        parent_unit_id=row_id,
                        parsing_confidence=0.9,
                    )
                )

            return units

        if table_lines:
            table_entities = extract_primary_entities(
                text,
                heading=section.get("heading"),
                section=section,
                document_zone=document_zone,
            )
            units.append(
                ContentUnit(
                    unit_id=table_id,
                    document_id=document_id,
                    conversation_id=document.get("conversation_id"),
                    agent=document.get("agent"),
                    source=source,
                    hierarchy=hierarchy,
                    document_zone=document_zone,
                    content_type="table",
                    entities=table_entities,
                    primary_entities=table_entities,
                    referenced_entities=extract_referenced_entities(
                        text,
                        document_zone=document_zone,
                    ),
                    content=clean_text(hierarchy.title or "Table"),
                    raw_text=clean_text("\n".join(table_lines)),
                    source_location=location,
                    source_section_id=source_section_id,
                    source_chunk_id=source_chunk_id,
                    document_order=base_order + 1,
                    parsing_confidence=0.75,
                )
            )

            header_cells = split_table_cells(table_lines[0])
            mapping_supported = (
                document_zone not in {"front_matter", "index"}
                and header_supports_code_mapping(header_cells)
            )

            for row_index, line in enumerate(table_lines[1:], start=1):
                row_cells = split_table_cells(line)

                if len([cell for cell in row_cells if cell]) < 2:
                    continue

                row_content = " | ".join(row_cells)
                row_entities = extract_primary_entities(
                    row_content,
                    heading=section.get("heading"),
                    section=section,
                    document_zone=document_zone,
                )
                row_id = stable_unit_id(
                    document_id,
                    section.get("section_index"),
                    section.get("chunk_index"),
                    "table_row",
                    row_index,
                    row_content,
                )
                units.append(
                    ContentUnit(
                        unit_id=row_id,
                        document_id=document_id,
                        conversation_id=document.get("conversation_id"),
                        agent=document.get("agent"),
                        source=source,
                        hierarchy=hierarchy,
                        document_zone=document_zone,
                        content_type="table_row",
                        entities=row_entities,
                        primary_entities=row_entities,
                        referenced_entities=extract_referenced_entities(
                            row_content,
                            document_zone=document_zone,
                        ),
                        content=row_content,
                        raw_text=line,
                        source_location=location,
                        source_section_id=source_section_id,
                        source_chunk_id=source_chunk_id,
                        document_order=base_order + 1 + row_index,
                        parent_unit_id=table_id,
                        parsing_confidence=0.8,
                    )
                )

                if (
                    mapping_supported
                    and looks_like_code(row_cells[0])
                    and looks_like_meaning(row_cells[1])
                ):
                    code = clean_text(row_cells[0]).strip("'\"").upper()
                    meaning = clean_text(row_cells[1])
                    mapping_entities = dict(row_entities)
                    mapping_entities["code"] = code
                    mapping_id = stable_unit_id(
                        document_id,
                        section.get("section_index"),
                        section.get("chunk_index"),
                        "code_mapping",
                        code,
                        meaning,
                    )
                    units.append(
                        ContentUnit(
                            unit_id=mapping_id,
                            document_id=document_id,
                            conversation_id=document.get("conversation_id"),
                            agent=document.get("agent"),
                            source=source,
                            hierarchy=hierarchy,
                            document_zone=document_zone,
                            content_type="code_mapping",
                            entities=mapping_entities,
                            primary_entities=mapping_entities,
                            referenced_entities={},
                            content=meaning,
                            raw_text=line,
                            source_location=location,
                            source_section_id=source_section_id,
                            source_chunk_id=source_chunk_id,
                            document_order=base_order + 2 + row_index,
                            parent_unit_id=row_id,
                            parsing_confidence=0.92,
                        )
                    )

            return units

        if explicit_mapping:
            code, meaning = explicit_mapping
            mapping_entities = extract_primary_entities(
                text,
                heading=section.get("heading"),
                section=section,
                document_zone=document_zone,
            )
            mapping_entities["code"] = code
            mapping_id = stable_unit_id(
                document_id,
                section.get("section_index"),
                section.get("chunk_index"),
                "code_mapping",
                code,
                meaning,
            )
            units.append(
                ContentUnit(
                    unit_id=mapping_id,
                    document_id=document_id,
                    conversation_id=document.get("conversation_id"),
                    agent=document.get("agent"),
                    source=source,
                    hierarchy=hierarchy,
                    document_zone=document_zone,
                    content_type="code_mapping",
                    entities=mapping_entities,
                    primary_entities=mapping_entities,
                    referenced_entities={},
                    content=meaning,
                    raw_text=clean_text(text),
                    source_location=location,
                    source_section_id=source_section_id,
                    source_chunk_id=source_chunk_id,
                    document_order=base_order + 1,
                    parsing_confidence=0.9,
                )
            )

        return units
